org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.10

## Fabric API
fabric_version=0.114.0+1.21.4

## Mod Properties
mod_id=shelfmod
mod_name=HK Bamboo Scaffolding
mod_license=MIT
mod_version=0.1.0
maven_group=io.github.hrmcngs.shelfmod
archives_base_name=shelfmod
mod_description=Hong Kong style bamboo scaffolding and green safety mesh.
mod_authors=atsn.ngs
