org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.157
neo_version_range=[21.4,)
loader_version_range=[4,)

## Mod Properties
mod_id=shelfmod
mod_name=HK Bamboo Scaffolding
mod_license=MIT
mod_version=0.1.0
mod_group_id=io.github.hrmcngs.shelfmod
mod_authors=atsn.ngs
mod_description=Hong Kong style bamboo scaffolding and green safety mesh.
